name: smartbin_ui_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-285.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  flutter_spinkit: ^5.2.0
  audioplayers: ^4.1.0
  # video_player_web: ^2.0.16
  video_player: ^2.7.0

dependency_overrides:
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # image
    - assets/images/
    - assets/images/icons/
    - assets/images/buttons/
    - assets/images/screens/
    - assets/images/gif/

    # sound
    - assets/sounds/gun.mp3

    # video
    - assets/videos/smart-bin.mp4


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
